### ISSUE TITLE
Routing Paragraph - der Link

### ISSUE THREAD

**Issue by Hamilkar247** [rozek/node-red-http-server-examples#1]
In Ihrer „readme.md“ im Paragraph „routing“ funktioniert der Link zum Beispiel der json-File nicht :)  

Link zu diesem Beispiel 
https://github.com/rozek/node-red-http-endpoint-examples/blob/main/examples/routing-with-placeholders.json

danke für alle beispiele :)

**Comment by rozek** [comment]
Vielen Dank für den Hinweis - ich habe den Link korrigiert
